version: '{branch}-{build}'
build: false
cache:
  - '%LOCALAPPDATA%\pip\Cache'

matrix:
    fast_finish: true

environment:
  global:
    WITH_COMPILER: 'cmd /E:ON /V:ON /C .\ci\appveyor-with-compiler.cmd'

  matrix:
    - CONDA_ROOT: 'C:\Miniconda3_64'
      PYTHON_VERSION: '3.4'
      PYTHON_ARCH: '32'
      CONDA_PY: '34'
    - CONDA_ROOT: 'C:\Miniconda3_64'
      WINDOWS_SDK_VERSION: v7.1
      PYTHON_VERSION: '3.4'
      PYTHON_ARCH: '64'
      CONDA_PY: '34'

    - CONDA_ROOT: 'C:\Miniconda3_64'
      PYTHON_VERSION: '3.5'
      PYTHON_ARCH: '32'
      CONDA_PY: '35'
    - CONDA_ROOT: 'C:\Miniconda3_64'
      PYTHON_VERSION: '3.5'
      PYTHON_ARCH: '64'
      CONDA_PY: '35'

    - CONDA_ROOT: 'C:\Miniconda3_64'
      PYTHON_VERSION: '3.6'
      PYTHON_ARCH: '32'
      CONDA_PY: '36'
    - CONDA_ROOT: 'C:\Miniconda3_64'
      WINDOWS_SDK_VERSION: v7.1
      PYTHON_VERSION: '3.6'
      PYTHON_ARCH: '64'
      CONDA_PY: '36'


# We always use a 64-bit machine, but can build x86 distributions
# with the PYTHON_ARCH variable (which is used by CMD_IN_ENV).
platform:
  - x64

init:
  - echo %PYTHON_VERSION% %MINICONDA%
install:
  - powershell .\ci\appveyor-bootstrap.ps1
  - set PATH=%CONDA_ROOT%;%CONDA_ROOT%\Scripts;%PATH%

  # install our build environment
  - cmd: conda config --set always_yes yes --set changeps1 no
  - cmd: conda update -q conda

  # this is now the downloaded conda
  - cmd: conda info -a
  - cmd: conda create -q -n testenv python=%PYTHON_VERSION% setuptools pip pytest>3.1 numpy pandas scipy matplotlib bokeh xlwings jinja2
  - activate testenv
  - pip install coverage

  # Now build the module
  - '%WITH_COMPILER% pip install -ve .'

test_script:
  - pytest


after_test:
  # cleanup the environment
  - deactivate

on_failure:

artifacts:
  - path: dist\*

### To enable remote debugging uncomment this (also, see: http://www.appveyor.com/docs/how-to/rdp-to-build-worker):
# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
