version: '{branch}-{build}'
build: off
cache:
  - '%LOCALAPPDATA%\pip\Cache'

matrix:
    fast_finish: true

environment:
  global:
    WITH_COMPILER: 'cmd /E:ON /V:ON /C .\ci\appveyor-with-compiler.cmd'

  matrix:
    # - CONDA_ROOT: 'C:\Miniconda3_64'
    #   PYTHON_VERSION: '3.5'
    #   PYTHON_ARCH: '32'
    #   CONDA_PY: '35'

    # - CONDA_ROOT: 'C:\Miniconda3_64'
    #   PYTHON_VERSION: '3.5'
    #   PYTHON_ARCH: '64'
    #   CONDA_PY: '35'

    - CONDA_ROOT: 'C:\Miniconda3_64'
      PYTHON_VERSION: '3.6'
      PYTHON_ARCH: '32'
      CONDA_PY: '36'

    - CONDA_ROOT: 'C:\Miniconda3_64'
      PYTHON_VERSION: '3.6'
      PYTHON_ARCH: '64'
      CONDA_PY: '36'

    - CONDA_ROOT: 'C:\Miniconda3_64'
      PYTHON_VERSION: '3.7'
      PYTHON_ARCH: '32'
      CONDA_PY: '37'

    - CONDA_ROOT: 'C:\Miniconda3_64'
      PYTHON_VERSION: '3.7'
      PYTHON_ARCH: '64'
      CONDA_PY: '37'


# We always use a 64-bit machine, but can build x86 distributions
# with the PYTHON_ARCH variable (which is used by CMD_IN_ENV).
platform:
  - x64

init:
  - echo %PYTHON_VERSION% %MINICONDA%
install:
  - powershell .\ci\appveyor-bootstrap.ps1
  - CALL "%CONDA_ROOT%\\Scripts\\activate.bat"

  # install our build environment
  - conda config --set always_yes yes               # always yes
  - conda config --append channels conda-forge      # add conda forge to channel list
  - conda update -q conda                           # update (quiet)
  - activate

  # get the conda info
  - conda info -a

  # install required packages
  - conda create -q -n testenv-%PYTHON_VERSION% python=%PYTHON_VERSION%
            setuptools
            pip
            coverage
            pytest>3.1
            pytest-cov
            numpy
            pandas
            scipy
            matplotlib
  - activate testenv-%PYTHON_VERSION%

  # Now build the module
  - '%WITH_COMPILER% pip install -ve .'

test_script:
  - pytest --cov --cov-report=term-missing -vv


after_test:
  # cleanup the environment
  - deactivate

on_failure:

artifacts:
  - path: dist\*

### To enable remote debugging uncomment this (also, see: http://www.appveyor.com/docs/how-to/rdp-to-build-worker):
# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
