version: '{branch}-{build}'
build: off
cache:
  - '%LOCALAPPDATA%\pip\Cache'

matrix:
    fast_finish: true

environment:
  global:
    WITH_COMPILER: 'cmd /E:ON /V:ON /C .\ci\appveyor-with-compiler.cmd'

  matrix:
{% for env, config in tox_environments|dictsort %}{{ '' }}{% if env.startswith(('py2', 'py3')) %}
    - CONDA_ROOT: 'C:\Miniconda3_64'
      PYTHON_VERSION: '{{ env[2] }}.{{ env[3] }}'
      PYTHON_ARCH: '32'
      CONDA_PY: '{{ env[2:4] }}'

    - CONDA_ROOT: 'C:\Miniconda3_64'
      {%- if env.startswith(('py2', 'py34')) %}

      WINDOWS_SDK_VERSION: v7.{{ '1' if env.startswith('py3') else '0' }}
      {%- endif %}

      PYTHON_VERSION: '{{ env[2] }}.{{ env[3] }}'
      PYTHON_ARCH: '64'
      CONDA_PY: '{{ env[2:4] }}'

{% endif %}{% endfor %}

# We always use a 64-bit machine, but can build x86 distributions
# with the PYTHON_ARCH variable (which is used by CMD_IN_ENV).
platform:
  - x64

init:
  - echo %PYTHON_VERSION% %MINICONDA%
install:
  - powershell .\ci\appveyor-bootstrap.ps1
  - set PATH=%CONDA_ROOT%;%CONDA_ROOT%\Scripts;%PATH%

  # install our build environment
  - cmd: conda config --set always_yes yes --set changeps1 no
  - cmd: conda update -q conda

  # get the conda info
  - cmd: conda info -a

  # install required packages
  - cmd: conda create -q -n testenv python=%PYTHON_VERSION%
            setuptools
            pip
            coverage
            pytest>3.1
            pytest-cov
            numpy
            pandas
            scipy
            matplotlib
  - activate testenv

  # Now build the module
  - '%WITH_COMPILER% pip install -ve .'

test_script:
  - pytest --cov --cov-report=term-missing -vv


after_test:
  # cleanup the environment
  - deactivate

on_failure:

artifacts:
  - path: dist\*

### To enable remote debugging uncomment this (also, see: http://www.appveyor.com/docs/how-to/rdp-to-build-worker):
# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
